[[redirects]]
  from = "https://www.enkiatelier.com/*"
  to   = "https://enkiatelier.com/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "http://www.enkiatelier.com/*"
  to   = "https://enkiatelier.com/:splat"
  status = 301
  force  = true
